Repository FreshManProject/FreshMan-Frontend, pull requests merged in 2024-08, with the labels that each got.

#38 [Refac] 파일 import 및 라우터 수정
  src/Router.tsx
  src/apis/search/index.ts
  src/apis/user/getInquiryList.ts
  src/apis/user/getLikeList.ts
  src/apis/user/getUserData.ts
  src/apis/user/index.ts
  src/components/FixedFilter/FilterBottomSheet.tsx
  src/components/Product/CategoryList.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductOption.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/index.tsx
  src/components/search/RecentSearchList.tsx
  src/hooks/BottomSheet/useBottomSheet.tsx
  src/hooks/logics/review/useSubmitReview.tsx
  src/hooks/query/product/index.ts
  src/hooks/query/review/index.ts
  src/hooks/query/search/index.ts
  src/pages/Inquiry/InquiryListPage.tsx
  src/pages/Inquiry/index.tsx
  src/pages/Member/RegisterPage.tsx
  src/pages/Member/RegisterSuccessPage.tsx
  src/pages/Member/SocialLoginPage.tsx
  src/pages/Member/SocialLoginRedirectPage.tsx
  src/pages/Member/index.tsx
  src/pages/MyPage/MyLikePage.tsx
  src/pages/MyPage/index.tsx
  src/pages/Product/index.tsx
  src/pages/Review/index.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/index.tsx
  src/router/inquiry/InquiryRouter.tsx
  src/router/login/LoginRouter.tsx
  src/router/mypage/MyPageRouter.tsx
  src/router/product/ProductRouter.tsx
  src/router/register/RegisterRouter.tsx
  src/router/search/SearchRouter.tsx
Labels: Refactor

#42 Refac: 헤더 컴포넌트 합성으로 리팩 (#41)
  src/Router.tsx
  src/components/common/Layout/LayoutWithoutNav.tsx
  src/components/common/TopHeader.tsx
  src/components/common/index.tsx
  src/components/mypage/EditAddressForm.tsx
  src/components/mypage/EditInformationForm.tsx
  src/components/mypage/MyInformation.tsx
  src/components/mypage/MyPageInformation.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/index.ts
  src/pages/Inquiry/InquiryListPage.tsx
  src/pages/Inquiry/InquiryPage.tsx
  src/pages/MyPage/MyLikePage.tsx
  src/pages/Product/ProductPage.tsx
  src/pages/Review/SubmitReviewPage.tsx
  src/router/review/reviewRouter.tsx
Labels: Refactor

#43 [Style] home UI 및 더미 api 연동
  public/images/icons-body.svg
  public/images/icons-foot.svg
  public/images/icons-hair.svg
  public/images/icons-lip.svg
  public/images/icons-mask.svg
  public/images/icons-perfume.svg
  public/images/icons-skin.svg
  src/apis/products/index.ts
  src/components/FixedFilter/FilterBottomSheet.tsx
  src/components/Home/CategoryMenu.tsx
  src/components/Home/HomeContent.tsx
  src/components/Home/HomeProductList.tsx
  src/components/Home/ProductMoreList.tsx
  src/components/Home/SaleContent.tsx
  src/components/Product/CategoryList.tsx
  src/components/Product/ProductDetail/ProductInfo.tsx
  src/components/Product/ProductImgSlider.tsx
  src/components/Product/ProductItem.tsx
  src/components/Product/ProductList.tsx
  src/components/Product/ProductSlider.tsx
  src/components/Product/index.tsx
  src/components/common/HorizontalScroll.tsx
  src/components/common/index.tsx
  src/hooks/query/product/index.ts
  src/hooks/useDragScroll.ts
  src/mocks/handlers.ts
  src/pages/Home/HomePage.tsx
  src/pages/Home/index.tsx
  src/types/category.ts
  tailwind.config.js
Labels: HTML&CSS, Feature

#44 [Refac] 리액트 모달 시트 제거
  package.json
  src/Router.tsx
  src/apis/user/index.ts
  src/assets/images/login-success.svg
  src/components/FixedFilter/FilterBottomSheet.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductOption.tsx
  src/components/Register/RegisterForm.tsx
  src/components/common/Button/PrimaryBkButton.tsx
  src/components/common/HorizontalScroll.tsx
  src/components/mypage/MyInformation.tsx
  src/components/mypage/edit/EditAddressForm.tsx
  src/components/mypage/edit/EditInformationForm.tsx
  src/components/mypage/edit/index.tsx
  src/components/mypage/index.tsx
  src/components/mypage/info/MyInformation.tsx
  src/components/mypage/info/MyPageInformation.tsx
  src/components/mypage/info/index.tsx
  src/hooks/query/user/index.ts
  src/index.css
  src/index.tsx
  src/mocks/handlers.ts
  src/pages/Member/RegisterSuccessPage.tsx
  src/pages/MyPage/EditAddressPage.tsx
  src/pages/MyPage/EditInformationPage.tsx
  src/pages/MyPage/MyInformationPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Review/SubmitReviewPage.tsx
  tailwind.config.js
  yarn.lock
Labels: Refactor, Fix

#49 [Feat] 문의하기 구현
  src/Router.tsx
  src/apis/index.ts
  src/apis/qna/index.ts
  src/apis/user/index.ts
  src/components/Inquiry/InquiryList.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductDetail/TabAndContent.tsx
  src/components/QnA/QnAItem.tsx
  src/components/QnA/QnAList.tsx
  src/components/common/TopHeader.tsx
  src/components/mypage/info/MyPageInformation.tsx
  src/hooks/query/mypage/index.ts
  src/hooks/query/product/index.ts
  src/hooks/query/user/index.ts
  src/index.tsx
  src/mocks/handlers.ts
  src/pages/Inquiry/InquiryListPage.tsx
  src/pages/Inquiry/index.tsx
  src/pages/MyPage/MyqnaPage.tsx
  src/pages/MyPage/index.tsx
  src/pages/qna/QnaSubmitPage.tsx
  src/pages/qna/index.tsx
  src/types/User/inquiry.ts
Labels: Feature

#51 [Feat/cart] 장바구니 UI 구현 and API Test (#45)
  src/Router.tsx
  src/apis/carts/index.ts
  src/apis/products/index.ts
  src/apis/user/index.ts
  src/components/Cart/CartItem.tsx
  src/components/Cart/CartList.tsx
  src/components/Cart/CartOption.tsx
  src/components/Cart/CartOptionCount.tsx
  src/components/Cart/CartSummary.tsx
  src/components/Home/ProductMoreList.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductDetail/ProductInfo.tsx
  src/components/Product/ProductOption.tsx
  src/components/Product/ProductSlider.tsx
  src/components/Register/RegisterForm.tsx
  src/components/common/Button/GrayBorderButton.tsx
  src/components/common/SearchInput.tsx
  src/components/common/TopHeader.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/drawer.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/hooks/query/carts/index.ts
  src/hooks/query/product/index.ts
  src/index.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/Cart/CartPage.tsx
  src/pages/Cart/index.tsx
  src/pages/Member/RegisterSuccessPage.tsx
  src/pages/Product/ProductDetailPage.tsx
  src/types/Product/productDetail.ts
  src/types/Product/productList.ts
  src/types/api.ts
  tailwind.config.js
Labels: Feature

#52 [Feat] 검색 기능 구현
  src/Router.tsx
  src/apis/products/index.ts
  src/apis/search/deleteRecentSearch.ts
  src/apis/search/getQuerySearch.ts
  src/apis/search/getRecentSearchList.ts
  src/apis/search/index.ts
  src/apis/user/index.ts
  src/components/FixedFilter/FilterBtn.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/PriceBottomSheet.tsx
  src/components/FixedFilter/SortBottomSheetContent.tsx
  src/components/FixedFilter/index.tsx
  src/components/Home/CategoryMenu.tsx
  src/components/Product/CategoryList.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/common/Button/GrayBorderToggleButton.tsx
  src/components/common/HorizontalScroll.tsx
  src/components/common/SortBottomSheetContent.tsx
  src/components/common/index.tsx
  src/components/search/RecentSearchList.tsx
  src/components/search/SearchChangeCategory.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResultList.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/drawer.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/data/index.ts
  src/hooks/query/search/index.ts
  src/hooks/query/search/useDeleteRecentSearch.ts
  src/hooks/query/search/useGetQuerySearch.ts
  src/hooks/query/search/useGetRecentSearchList.ts
  src/mocks/handlers.ts
  src/pages/Product/ProductPage.tsx
  src/pages/Search/SearchPage.tsx
  src/pages/Search/SearchResultPage.tsx
  src/pages/Search/index.tsx
  src/store/filter.ts
  src/store/title.ts
  src/types/Product/productList.ts
Labels: Feature, Fix
