Repository FreshManProject/FreshMan-Frontend, pull requests merged in 2024-07, with the labels that each got.

#5 Style/common top
  package.json
  public/index.html
  src/App.tsx
  src/components/common/TopHeader/TobHeader.tsx
  src/index.css
  tailwind.config.js
  yarn.lock
Labels: HTML&CSS

#7 [Style] Product List/Item & Filter 영역 UI 구현
  .eslintrc.js
  craco.config.js
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/FilterItem.tsx
  src/components/FixedFilter/FilterList.tsx
  src/components/FixedFilter/index.tsx
  src/components/Product/ProductItem.tsx
  src/components/Product/ProductList.tsx
  src/components/Product/index.tsx
  src/components/common/Button/GrayBorderButton.tsx
  src/components/common/LikeBtn.tsx
  src/components/common/TopHeader.tsx
  src/components/common/index.tsx
  src/pages/ProductPage.tsx
  tailwind.config.js
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: HTML&CSS

#12 [Feat] BottomSheet 구현 / zustand setting
  .eslintrc.js
  package.json
  src/Router.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/FilterItem.tsx
  src/components/FixedFilter/FilterList.tsx
  src/components/Product/ProductItem.tsx
  src/components/Product/ProductList.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Button/GrayBorderButton.tsx
  src/components/common/LikeBtn.tsx
  src/components/common/TopHeader.tsx
  src/components/common/index.tsx
  src/hooks/BottomSheet/useBottomSheet.tsx
  src/hooks/BottomSheet/useIsOpenBottomSheet.tsx
  src/index.css
  src/pages/ProductPage.tsx
  src/store/useBottomSheetStore.tsx
  yarn.lock
Labels: Feature, Setting

#13 #3 [Setting] router 구성 및 공통 컴포넌트 레이아웃 생성
  craco.config.js
  postcss.config.js
  src/App.tsx
  src/GlobalError.tsx
  src/Router.tsx
  src/components/FixedFilter/FilterItem.tsx
  src/components/Register/RegisterForm.tsx
  src/components/common/Button/index.tsx
  src/components/common/Layout/LayoutWithNav.tsx
  src/components/common/Layout/index.tsx
  src/components/common/Nav/FixedNav.tsx
  src/components/common/Nav/index.tsx
  src/components/common/TopHeader.tsx
  src/components/common/index.tsx
  src/components/ui/input.tsx
  src/index.css
  src/index.tsx
  tailwind.config.js
Labels: Setting

#16 [Style] 상품 상세 상단/옵션 UI 구현
  .eslintrc.js
  package.json
  src/Router.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/FilterItem.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductDetail/OptionCount.tsx
  src/components/Product/ProductDetail/OptionCountItem.tsx
  src/components/Product/ProductDetail/index.tsx
  src/components/Product/ProductImgSlider.tsx
  src/components/Product/ProductItem.tsx
  src/components/Product/ProductList.tsx
  src/components/Product/ProductOption.tsx
  src/components/Product/index.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Button/GrayBorderButton.tsx
  src/components/common/Button/GrayBorderToggleButton.tsx
  src/components/common/Button/PrimaryBkButton.tsx
  src/components/common/Button/index.tsx
  src/components/common/Layout/LayoutWithoutNav.tsx
  src/components/common/Layout/index.tsx
  src/components/common/LikeBtn.tsx
  src/components/common/TopHeader.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/components/ui/select.tsx
  src/hooks/BottomSheet/useBottomSheet.tsx
  src/hooks/BottomSheet/useIsOpenBottomSheet.tsx
  src/index.css
  src/pages/Product/ProductDetailPage.tsx
  src/pages/Product/ProductPage.tsx
  src/types/Product/productDetail.ts
  tailwind.config.js
  yarn.lock
Labels: HTML&CSS

#21 [Style] 상품 상세에 문의하기&리뷰 리스트 UI 구현
  package.json
  src/Router.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductDetail/OptionCountItem.tsx
  src/components/Product/ProductDetail/TabAndContent.tsx
  src/components/Product/ProductDetail/TabAndContentLayout.tsx
  src/components/Product/ProductDetail/index.tsx
  src/components/Product/ProductOption.tsx
  src/components/QnA/QnABtn.tsx
  src/components/QnA/QnAItem.tsx
  src/components/QnA/QnAList.tsx
  src/components/QnA/index.tsx
  src/components/Review/ProductReviewScore.tsx
  src/components/Review/ReviewItem.tsx
  src/components/Review/ReviewList.tsx
  src/components/Review/Star.tsx
  src/components/Review/index.tsx
  src/components/common/Button/GrayBorderButton.tsx
  src/components/common/Button/GrayBorderToggleButton.tsx
  src/components/ui/accordion.tsx
  src/components/ui/tabs.tsx
  src/index.css
  src/pages/Product/ProductDetailPage.tsx
  tailwind.config.js
  yarn.lock
Labels: HTML&CSS

#24 [Feat] 상품 가격 필터링
  package.json
  public/index.html
  public/mockServiceWorker.js
  src/Router.tsx
  src/apis/products/index.ts
  src/components/FixedFilter/FilterBottomSheet.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/FilterItem.tsx
  src/components/FixedFilter/FilterList.tsx
  src/components/FixedFilter/index.tsx
  src/components/Product/Filter/Price.tsx
  src/components/Product/Filter/index.tsx
  src/components/Product/ProductList.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Button/PrimaryBkButton.tsx
  src/components/ui/drawer.tsx
  src/components/ui/slider.tsx
  src/hooks/query/product/useGetProductList.tsx
  src/index.css
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/Product/ProductPage.tsx
  src/types/Product/productList.ts
  src/util/formatData.ts
  tailwind.config.js
  yarn.lock
Labels: Feature

#26 [Feat] 상품 리스트 sort에 따라 update 되도록 구현
  .eslintrc.js
  package.json
  src/apis/products/index.ts
  src/components/FixedFilter/FilterBottomSheet.tsx
  src/components/FixedFilter/FilterContainer.tsx
  src/components/FixedFilter/SortBottomSheetContent.tsx
  src/components/Product/ProductList.tsx
  src/components/Review/ProductReviewScore.tsx
  src/components/Review/Star.tsx
  src/components/common/Button/GrayBorderToggleButton.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/drawer.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/constants/product.ts
  src/provider/queryProvider.tsx
  src/types/Product/productList.ts
  yarn.lock
Labels: Feature

#27 [Feat] 찜페이지, 문의 페이지 구현
  .eslintrc.js
  .gitignore
  package.json
  src/Router.tsx
  src/apis/axios.ts
  src/apis/index.ts
  src/apis/requests.ts
  src/apis/user/getInquiryList.ts
  src/apis/user/getLikeList.ts
  src/apis/user/getUserData.ts
  src/apis/user/index.ts
  src/components/Inquiry/InquiryForm.tsx
  src/components/Inquiry/InquiryList.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Review/ReviewList.tsx
  src/components/common/Button/SubmitButton.tsx
  src/components/mypage/EditAddressForm.tsx
  src/components/mypage/EditInformationForm.tsx
  src/components/mypage/MyPageInformation.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/Contact/InquiryListPage.tsx
  src/pages/Contact/InquiryPage.tsx
  src/pages/Login/KakaoSocialLoginPage.tsx
  src/pages/Login/NaverSocialLoginPage.tsx
  src/pages/Login/SocialLoginPage.tsx
  src/pages/MyPage/MyLikePage.tsx
  src/pages/Register/RegisterSuccessPage.tsx
  src/types/User/inquiry.ts
Labels: Feature

#29 [Fix] 상품 아이템 데이터 처리
  src/apis/user/getLikeList.ts
  src/components/Product/CategoryList.tsx
  src/components/Product/ProductBuyBtn.tsx
  src/components/Product/ProductItem.tsx
  src/components/Product/ProductList.tsx
  src/components/Product/index.tsx
  src/components/common/LikeBtn.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/MyPage/MyLikePage.tsx
  src/pages/Product/ProductPage.tsx
  src/types/Product/productList.ts
Labels: Fix

#33 [API] 소셜 로그인
  package.json
  src/pages/Login/KakaoSocialLoginPage.tsx
  src/pages/Login/NaverSocialLoginPage.tsx
  src/pages/Login/SocialLoginRedirectPage.tsx
  src/router/login/LoginRouter.tsx
  yarn.lock
Labels: API

#34 [API] 검색 API 수정
  src/apis/axios.ts
  src/apis/requests.ts
  src/apis/search/deleteRecentSearch.ts
  src/apis/search/getQuerySearch.ts
  src/apis/search/getRecentSearchList.ts
  src/components/common/SearchInput.tsx
  src/components/search/RecentSearchList.tsx
  src/hooks/query/search/useDeleteRecentSearch.ts
  src/hooks/query/search/useGetQuerySearch.ts
  src/hooks/query/search/useGetRecentSearchList.ts
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/Inquiry/InquiryListPage.tsx
  src/pages/Inquiry/InquiryPage.tsx
  src/pages/Search/SearchPage.tsx
  src/router/inquiry/InquiryRouter.tsx
Labels: API
